[build]
functions = "functions"

[[redirects]]
to = "/s"
from = "/f"
status = "301"

[[redirects]]
to = "/s"
from = "/s"
status = "301"

[[redirects]]
to = "/sdgfs"
from = "/sdkfjh"
status = "301"

[[redirects]]
to = "/br"
from = "/d"
status = "301"

[[redirects]]
to = "/fd"
from = "/a"
status = "301"

[[redirects]]
to = "/asdjsf"
from = "/afghsjkdlfh"
status = "301"

[[redirects]]
to = "/mnb"
from = "/gsdf"
status = "301"

[[redirects]]
to = "/sd"
from = "/k"
status = "301"

[[redirects]]
to = "/ll"
from = "/v"
status = "301"

[[redirects]]
to = "/n"
from = "/s"
status = "301"

[[redirects]]
to = "/test16"
from = "/test15"
status = "301"

[[redirects]]
to = "/test14"
from = "/test13"
status = "301"

[[redirects]]
to = "/2"
from = "/1"
status = "301"

[[redirects]]
to = "/b"
from = "/a"
status = "301"

[[redirects]]
to = "/test12"
from = "/test11"
status = "301"

[[redirects]]
to = "/test10"
from = "/test9"
status = "301"

[[redirects]]
to = "/test8"
from = "/test7"
status = "301"

[[redirects]]
to = "/test6"
from = "/test5"
status = "301"

[[redirects]]
to = "/test4"
from = "/test3"
status = "301"

[[redirects]]
to = "/test2"
from = "/test"
status = "301"

[[redirects]]
to = "/pull2"
from = "/pull"
status = "301"

[[redirects]]
from = "/products/giftcard"
to = "/products/e-giftcard"
status = 301

[[redirects]]
from = "/sizing"
to = "/pages/sizing"
status = 301

[[redirects]]
from = "/reviews"
to = "/pages/reviews"
status = 301

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "."
  prettyURLs = true
  trailingSlash = true
