[build]
functions = "functions"

[[redirects]]
to = "/b"
from = "/a"
status = "301"

[[redirects]]
to = "/test12"
from = "/test11"
status = "301"

[[redirects]]
to = "/test10"
from = "/test9"
status = "301"

[[redirects]]
to = "/test8"
from = "/test7"
status = "301"

[[redirects]]
to = "/test6"
from = "/test5"
status = "301"

[[redirects]]
to = "/test4"
from = "/test3"
status = "301"

[[redirects]]
to = "/test2"
from = "/test"
status = "301"

[[redirects]]
to = "/pull2"
from = "/pull"
status = "301"

[[redirects]]
from = "/products/giftcard"
to = "/products/e-giftcard"
status = 301

[[redirects]]
from = "/sizing"
to = "/pages/sizing"
status = 301

[[redirects]]
from = "/reviews"
to = "/pages/reviews"
status = 301

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "."
  prettyURLs = true
  trailingSlash = true
